C_Exercicio_Template/C_Exercicio_Template/C_Exercicio_Template/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produtos.urls')),
]

C_Exercicio_Template/C_Exercicio_Template/produtos/urls.py
from django.urls import path
from . import views

app_name = 'produtos'

urlpatterns = [
    path('', views.principal, name='principal'),
    path('produto/<int:id>/', views.produto, name='produto'),
]

C_Exercicio_Template/C_Exercicio_Template/produtos/models.py
from django.db import models

# Create your models here.

C_Exercicio_Template/C_Exercicio_Template/produtos/views.py
from django.shortcuts import render, redirect

prod1 = {
    'id': 1, 
    'nome': 'Computador', 
    'preco': 4510.80, 
    'resumo': 'Computador de última geração', 
    'descricao': 'Computador com processador Intel i7, 16GB de RAM, SSD de 512GB e placa de vídeo dedicada.'
}

prod2 = {
    'id': 2, 
    'nome': 'Celular', 
    'preco': 4520.00, 
    'resumo': 'Celular com câmera de alta resolução', 
    'descricao': 'Celular com câmera de 108MP, 128GB de armazenamento, bateria de longa duração e tela AMOLED.'
}

prod3 = {
    'id': 3, 
    'nome': 'Microondas', 
    'preco': 1530.00, 
    'resumo': 'Microondas com função grill', 
    'descricao': 'Microondas com capacidade de 30 litros, função grill, painel digital e 10 níveis de potência.'
}

prod4 = {
    'id': 4, 
    'nome': 'Geladeira', 
    'preco': 2500.00, 
    'resumo': 'Geladeira com tecnologia inverter', 
    'descricao': 'Geladeira com capacidade de 450 litros, tecnologia inverter, dispenser de água e prateleiras ajustáveis.'
}

prod5 = {
    'id': 5, 
    'nome': 'Televisão', 
    'preco': 3200.00, 
    'resumo': 'Televisão 4K com Smart TV', 
    'descricao': 'Televisão de 55 polegadas, resolução 4K, Smart TV com acesso a aplicativos e controle por voz.',
    'promocao': 'sim',
}

produtos = [ prod1, prod2, prod3, prod4, prod5 ]

# Create your views here.
def principal(request):
    contexto = {
        'quantidade': len(produtos),
        'produtos': produtos,
    }
    
    # contexto = {
    #     'quantidade': 0,
    #     'produtos': [],
    # }

    return render(request, 'produtos/lista_produtos.html', contexto)


def produto(request, id):

    if request.method == 'GET':
        produto = next((p for p in produtos if p['id'] == id), None)
        print(produto)
    
        contexto = { 'produto': produto }
        return render(request, 'produtos/detalhe_produto.html', contexto)
    else:
        return redirect('produtos:principal')

C_Exercicio_Template/C_Exercicio_Template/produtos/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block titulo %}{% endblock %}</title>
</head>
<body>
    <header>
        <h1>{% block cabecalho %}{% endblock %}</h1>
        <p>Data atual: {% now "d/m/Y" %} | Hora: {% now "H:i" %}</p>
    </header>
    <hr>
    {% block conteudo %}{% endblock %}
</body>
</html>

C_Exercicio_Template/C_Exercicio_Template/produtos/templates/produtos/detalhe_produto.html
{% extends 'base.html' %}

{% block titulo %}Detalhes do Produto{% endblock %}

{% block cabecalho %}Detalhes do Produto:{% endblock %}

{% block conteudo %}
    <h2>{{ produto.nome|capfirst }}</h2>
    <p><strong>Preço:</strong> R$ {{ produto.preco|floatformat:"2g" }}</p>
    <p><strong>Promoção:</strong> {{ produto.promocao|default:"indisponível" }}</p>
    {% if produto.promocao %}
        <p><strong>Desconto:</strong> 10%</p>
    {% endif %}
    <p><strong>Resumo:</strong> {{ produto.descricao|truncatewords:5 }}</p>
    <p><strong>Descrição:</strong> {{ produto.descricao|truncatechars:60 }}</p>
    <form method="post" action="{% url 'produtos:produto' 1  %}">
        {% csrf_token %}
        <input type="number" name="qtd" id="qtd">
        <button type="submit">Simular Compra</button>
    </form>
    
    <a href="{% url 'produtos:principal' %}">Voltar para a lista</a>
{% endblock %}

C_Exercicio_Template/C_Exercicio_Template/produtos/templates/produtos/lista_produtos.html
{% extends 'base.html' %}

{% block titulo %}Lista de Produtos{% endblock %}

{% block cabecalho %}Confira todos os produtos:{% endblock %}

{% block conteudo %}
    <h2>Temos {{ quantidade }} produto{{ quantidade|pluralize:"s" }} disponíve{{ quantidade|pluralize:"l,is" }}</h2>

    <ul>
        {% for produto in produtos %}
            <li>
                <strong>{{ produto.nome|capfirst }}</strong><br>
                Preço: R$ {{ produto.preco|floatformat:'2g' }}<br>
                <a href="{% url 'produtos:produto' produto.id %}">Ver detalhes</a>
            </li>
        {% empty %}
            <p>Não há produtos disponíveis.</p>
        {% endfor %}
    </ul>
{% endblock %}